name: tutorial
channels:
  - defaults
dependencies:
  - python=3.6
  - scikit-learn=0.19.1
  - pip:
    - mlflow>=1.0
    - azure-storage-blob
    - azure-storage-file
    - azure-storage-queue
    - pandas
